name: docs
on:
    push:
        branches:
            - master
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: install library and test
        run: |
          pip install --upgrade pip && pip install mkdocs-material mkdocstrings mkdocs-jupyter mkdocstrings-python
          mkdocs build
      
      - name: deploy docs
        run: |
            git config --global user.name "${GITHUB_ACTOR}"        
            remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
            git remote rm origin
            git remote add origin "${remote_repo}"
            mkdocs gh-deploy --force
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
