name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - "**.md"
      - "mkdocs.yml"
  workflow_dispatch:
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - name: install library and test
        run: |
          pip install --upgrade pip && pip install mkdocs-material mkdocstrings mkdocs-jupyter
          mkdocs build
      
      - name: deploy docs
        run: |
            git config --global user.name "${GITHUB_ACTOR}"        
            remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
            git remote rm origin
            git remote add origin "${remote_repo}"
            mkdocs gh-deploy --force
            env:
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
