name: docs
on:
    push:
        branches:
            - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6 - 3.9'
        architecture: 'x64'
    - name: Install the library
      run: |
        pip install -e .
        pip install mkdocs-material mkdocstrings mkdocs-jupyter
        mkdocs build

    - name: deploy docs
      run: |
        git config --global user.name "${GITHUB_ACTOR}"        
        remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
        git remote rm origin
        git remote add origin "${remote_repo}"
        mkdocs gh-deploy --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
