name: test_docs
on: [push, pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - name: check docs
        run: |
          pip install --upgrade pip && pip install mkdocs-material mkdocstrings mkdocs-jupyter mkdocstrings-python
          mkdocs build
